lib/diaryfishing_web/router.ex
defmodule DiaryfishingWeb.Router do
  use DiaryfishingWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
      extensions: [PowResetPassword, PowEmailConfirmation]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
         error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()
  end

  scope "/", DiaryfishingWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/fish/day", PageController, :fishday
    resources "/fishdays", FishdaysController
    get "/dashboard", DashboardController, :index
  end

  scope "/protected", DiaryfishingWeb do
    pipe_through [:browser, :protected]


  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiaryfishingWeb do
  #   pipe_through :api
  # end
end

lib/diaryfishing_web/views/layout_view.ex
defmodule DiaryfishingWeb.LayoutView do
  use DiaryfishingWeb, :view
end

lib/diaryfishing_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Page title</title>
        <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                <meta name="description" content="">
                    <meta name="author" content="">

                        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
                              integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
                              crossorigin=""/>

                        <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
                        <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/weather-icons.css") %>"/>
                        <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/weather-icons-wind.css") %>"/>
                    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    </head>
    <body>
        <!-- Section 1 -->
        <section class="w-full px-6 pb-12 antialiased bg-white">
            <div class="mx-auto max-w-7xl">
                <nav class="relative z-50 h-24 select-none" x-data="{ showMenu: false }">
                    <div class="container relative flex flex-wrap items-center justify-between h-24 mx-auto overflow-hidden font-medium border-b border-indigo-200 md:overflow-visible lg:justify-center sm:px-4 md:px-2">
                        <div class="flex items-center justify-start w-1/4 h-full pr-4">
                            <a href="#_" class="inline-block py-4 md:py-0">
                                <span class="text-transparent text-xl bg-clip-text bg-gradient-to-br from-indigo-600 to-indigo-500 md:inline-block">></span><span class="p-1 text-xl font-black leading-none text-gray-900"><span>meteo.fish</span><span class="text-indigo-600">.</span></span>
                            </a>
                        </div>
                        <div class="top-0 left-0 items-start hidden w-full h-full p-4 text-sm bg-gray-900 bg-opacity-50 md:items-center md:w-3/4 md:absolute lg:text-base md:bg-transparent md:p-0 md:relative md:flex" :class="{'flex fixed': showMenu, 'hidden': !showMenu }">
                        <div class="flex-col w-full h-auto overflow-hidden bg-white rounded-lg md:bg-transparent md:overflow-visible md:rounded-none md:relative md:flex md:flex-row">
                            <a href="#_" class="inline-flex items-center block w-auto h-16 px-6 text-xl font-black leading-none text-gray-900 md:hidden">tails<span class="text-indigo-600">.</span></a>
                            <div class="flex flex-col items-start justify-center w-full space-x-6 text-center lg:space-x-8 md:w-2/3 md:mt-0 md:flex-row md:items-center">
                                <a href="#_" class="inline-block w-full py-2 mx-0 ml-6 font-medium text-left text-indigo-600 md:ml-0 md:w-auto md:px-0 md:mx-2 lg:mx-3 md:text-center">Home</a>
                                <a href="#_" class="inline-block w-full py-2 mx-0 font-medium text-left text-gray-700 md:w-auto md:px-0 md:mx-2 hover:text-indigo-600 lg:mx-3 md:text-center">Features</a>
                                <a href="#_" class="inline-block w-full py-2 mx-0 font-medium text-left text-gray-700 md:w-auto md:px-0 md:mx-2 hover:text-indigo-600 lg:mx-3 md:text-center">Blog</a>
                                <a href="#_" class="inline-block w-full py-2 mx-0 font-medium text-left text-gray-700 md:w-auto md:px-0 md:mx-2 hover:text-indigo-600 lg:mx-3 md:text-center">Contact</a>
                                <a href="#_" class="absolute top-0 left-0 hidden py-2 mt-6 ml-10 mr-2 text-gray-600 lg:inline-block md:mt-0 md:ml-2 lg:mx-3 md:relative">
                                    <svg class="inline w-5 h-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                                </a>
                            </div>

                            <div class="flex flex-col items-start justify-end w-full pt-4 md:items-center md:w-1/3 md:flex-row md:py-0">
                                 <%= if Pow.Plug.current_user(@conn)  do %>
                                <div x-data="{ open: false }" class="relative">
                                    <button x-on:click="open = true" class="block h-12 w-12 rounded-full overflow-hidden focus:outline-none">
                                      <img class="h-full w-full object-cover" src="https://eu.ui-avatars.com/api/?name=John&size=1000" alt="avatar">
                                    </button>
                                    <!-- Dropdown Body -->
                                    <!-- Settings -->
                                    <div x-show.transition="open" x-on:click.away="open = false" class="z-40 absolute border-4 border-indigo-600 right-0 w-40 bg-white border rounded shadow-xl">

                                     <a href="#" class="transition-colors duration-200 block px-4 py-2 text-normal text-gray-900 hover:bg-indigo-600 hover:text-white">Settings</a>

                                    <%= link "Log out",
                                    to: Routes.pow_session_path(@conn, :delete),
                                    method: :delete,
                                    class: "transition-colors duration-200 block px-4 py-2 text-normal text-gray-900 hover:bg-indigo-600 hover:text-white" %>
                                      <div class="py-2 bg-indigo-600">
                                        <hr></hr>
                                      </div>

                                    <!-- Myfishdays -->
                                    <%= link to: Routes.fishdays_path(@conn, :index), class: "transition-colors duration-200 block px-4 py-2 text-normal text-black-900 hover:bg-indigo-600 hover:text-white" do %>
                                    <span class="hover:white text-xl bg-clip-text bg-gradient-to-br from-indigo-600 to-indigo-500 md:inline-block">></span>
                                    My sessions

                                    <% end %>

                                    <!-- AddFishDay -->
                                    <%= link to: Routes.fishdays_path(@conn, :new), class: "transition-colors duration-200 block px-4 py-2 text-normal text-black-900 hover:bg-indigo-600 hover:text-white" do %>
                                    <span class="hover:white text-xl bg-clip-text bg-gradient-to-br from-indigo-600 to-indigo-500 md:inline-block">></span>
                                    New Session
                                    <% end %>
                                   </div>
                                  <!-- // Dropdown Body -->
                                </div>


                                <% else %>
                                <a href="#" class="w-full px-6 py-2 mr-0 text-gray-700 md:px-0 lg:pl-2 md:mr-4 lg:mr-5 md:w-auto">
                                    <%= link "Sign in",
                                    to: Routes.pow_session_path(@conn, :new),
                                    class: "inline-flex items-center justify-center w-full px-8 py-4 text-base font-bold leading-6 text-white bg-indigo-600 border border-transparent rounded-full md:w-auto hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600" %>
                                <% end %></a>
                            </div>



                        </div>
                    </div>
                    <div @click="showMenu = !showMenu" class="absolute right-0 flex flex-col items-center items-end justify-center w-10 h-10 bg-white rounded-full cursor-pointer md:hidden hover:bg-gray-100">
                    <svg class="w-6 h-6 text-gray-700" x-show="!showMenu" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor" x-cloak="">
                        <path d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                    <svg class="w-6 h-6 text-gray-700" x-show="showMenu" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" x-cloak="">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
            </div>
        </div>
    </nav>


    <div class="flex-grow flex flex-col">
        <div class="container relative px-24 py-4 mx-auto text-left md:max-w-none">
            <%= render @view_module, @view_template, assigns %>
        </div>
    </div>
</div>

</section>
</body>
</html>